apiVersion: apps/v1
kind: Deployment
kind2: Deployment2
metadata:
  name: javawebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: dockerhandson/java-web-app:latest

        resources:
          limits:
            memory: "200Mi"
            cpu: "400m"
        ports:
        - containerPort: 8080







code change for testing
