apiVersion: apps/v1
kind: pOD
kind: Dep2
kind2: Deployment2
kind4: dep4
kind2: REGISTRY.K8S.IO
metadata:
  name: javawebapp
spec:
  hello: raju has been SUSPENDED
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
      app1: javawebapp2
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
        - name: javawebappcontainer
          image: dockerhandson/REGISTRY.K8S.IO:latest

          resources:
            limits:
              memory: "200Mi"
              cpu: "400m"
          ports:
            - containerPort: 8080





#sdfsd
#commenting
'hello for new space code'

ajdabdakdabk


helllo from main branch
