apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp
spec:
  hello: raju has been added
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
      app1: javawebapp2
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
        - name: javawebappcontainer
          image: dockerhandson/java-web-app:latest

          resources:
            limits:
              memory: "200Mi"
              cpu: "400m"
          ports:
            - containerPort: 8080





#sdfsd
#commenting
'hello for new space code'

ajdabdakdabk