apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: mayankgupta1217/simple-devops-image

        resources:
          limits:
            memory: "200Mi"
            cpu: "400m"
        ports:
        - containerPort: 8080
